FROM node:22-slim AS builder

WORKDIR /app

COPY scripts ./scripts
COPY knowledge ./knowledge
COPY wiki/package.json wiki/package-lock.json ./wiki/
RUN npm --prefix wiki ci

COPY wiki ./wiki

ARG QUARTZ_BASE_URL
ENV QUARTZ_BASE_URL=${QUARTZ_BASE_URL}

RUN node scripts/build-wiki-site.mjs

FROM nginx:1.27-alpine

COPY deploy/wiki-nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist-wiki /usr/share/nginx/html

EXPOSE 80
